# Data Validations - Phase 2

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Environment ready")

Environment ready

In [17]:
# Load Excel Data

file_path = "Fantasy-Lord-Rookie-ML-Dataset.xlsx"

draft_df = pd.read_excel(file_path, sheet_name="draft_and_player_data")
fantasy_df = pd.read_excel(file_path, sheet_name="fantasy_targets")
master_df = pd.read_excel(file_path, sheet_name="master_dataset")

print("Draft Data:", draft_df.shape)
print("Fantasy Targets:", fantasy_df.shape)
print("Master Dataset:", master_df.shape)

Draft Data: (164, 14)
Fantasy Targets: (164, 7)
Master Dataset: (164, 17)

In [18]:
# Preview Draft Table

draft_df.head()

,player_id,player_name,season,position,nfl_team,draft_round,draft_pick_overall,age_on_draft_day,height_inches,weight_lbs,college,college_games_played,career_yards,career_touchdowns
0,qb_2010_bradford,Sam Bradford,2010,QB,Rams,1,1,22,76,224,Oklahoma,31,8403,88
1,rb_2010_spiller,C.J. Spiller,2010,RB,Bills,1,9,23,71,194,Clemson,52,3547,32
2,rb_2010_mathews,Ryan Mathews,2010,RB,Chargers,1,12,22,72,220,Fresno St.,31,3280,39
3,te_2010_gresham,Jermaine Gresham,2010,TE,Bengals,1,21,22,77,260,Oklahoma,41,1629,26
4,wr_2010_thomas,Demaryius Thomas,2010,WR,Broncos,1,22,22,75,225,Georgia Tech,39,2339,15

In [19]:
# Preview Fantasy Target Table

fantasy_df.head()

,player_id,player_name,season,position,rookie_total_ppr_points,season_positional_finish,fantasy_relevant_binary
0,qb_2010_bradford,Sam Bradford,2010,QB,245.7,16.0,0.0
1,rb_2010_spiller,C.J. Spiller,2010,RB,95.2,49.0,0.0
2,rb_2010_mathews,Ryan Mathews,2010,RB,158.3,32.0,0.0
3,te_2010_gresham,Jermaine Gresham,2010,TE,112.1,16.0,0.0
4,wr_2010_thomas,Demaryius Thomas,2010,WR,52.3,87.0,0.0

In [20]:
# Preview Master Table

master_df.head()

,player_id,player_name,season,position,nfl_team,draft_round,draft_pick_overall,age_on_draft_day,height_inches,weight_lbs,college,college_games_played,career_yards,career_touchdowns,rookie_total_ppr_points,season_positional_finish,fantasy_relevant_binary
0,qb_2010_bradford,Sam Bradford,2010,QB,Rams,1,1,22,76,224,Oklahoma,31,8403,88,245.7,16.0,0.0
1,rb_2010_spiller,C.J. Spiller,2010,RB,Bills,1,9,23,71,194,Clemson,52,3547,32,95.2,49.0,0.0
2,rb_2010_mathews,Ryan Mathews,2010,RB,Chargers,1,12,22,72,220,Fresno St.,31,3280,39,158.3,32.0,0.0
3,te_2010_gresham,Jermaine Gresham,2010,TE,Bengals,1,21,22,77,260,Oklahoma,41,1629,26,112.1,16.0,0.0
4,wr_2010_thomas,Demaryius Thomas,2010,WR,Broncos,1,22,22,75,225,Georgia Tech,39,2339,15,52.3,87.0,0.0

In [21]:
# Check Column Names

print("Draft Columns:")
print(draft_df.columns.tolist())

print("\nFantasy Columns:")
print(fantasy_df.columns.tolist())

print("\nMaster Columns:")
print(master_df.columns.tolist())

Draft Columns:
['player_id', 'player_name', 'season', 'position', 'nfl_team', 'draft_round', 'draft_pick_overall', 'age_on_draft_day', 'height_inches', 'weight_lbs', 'college', 'college_games_played', 'career_yards', 'career_touchdowns']

Fantasy Columns:
['player_id', 'player_name', 'season', 'position', 'rookie_total_ppr_points', 'season_positional_finish', 'fantasy_relevant_binary']

Master Columns:
['player_id', 'player_name', 'season', 'position', 'nfl_team', 'draft_round', 'draft_pick_overall', 'age_on_draft_day', 'height_inches', 'weight_lbs', 'college', 'college_games_played', 'career_yards', 'career_touchdowns', 'rookie_total_ppr_points', 'season_positional_finish', 'fantasy_relevant_binary']

In [22]:
# Check Missing Values

print("Draft Missing Values:")
display(draft_df.isnull().sum())

print("Fantasy Missing Values:")
display(fantasy_df.isnull().sum())

print("Master Missing Values:")
display(master_df.isnull().sum())

Draft Missing Values:

player_id               0
player_name             0
season                  0
position                0
nfl_team                0
draft_round             0
draft_pick_overall      0
age_on_draft_day        0
height_inches           0
weight_lbs              0
college                 0
college_games_played    0
career_yards            0
career_touchdowns       0
dtype: int64

Fantasy Missing Values:

player_id                    0
player_name                  0
season                       0
position                     0
rookie_total_ppr_points     10
season_positional_finish    10
fantasy_relevant_binary     10
dtype: int64

Master Missing Values:

player_id                    0
player_name                  0
season                       0
position                     0
nfl_team                     0
draft_round                  0
draft_pick_overall           0
age_on_draft_day             0
height_inches                0
weight_lbs                   0
college                      0
college_games_played         0
career_yards                 0
career_touchdowns            0
rookie_total_ppr_points     10
season_positional_finish    10
fantasy_relevant_binary     10
dtype: int64

In [23]:
# Check data types

master_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player_id                 164 non-null    str
 1   player_name               164 non-null    str
 2   season                    164 non-null    int64
 3   position                  164 non-null    str
 4   nfl_team                  164 non-null    str
 5   draft_round               164 non-null    int64
 6   draft_pick_overall        164 non-null    int64
 7   age_on_draft_day          164 non-null    int64
 8   height_inches             164 non-null    int64
 9   weight_lbs                164 non-null    int64
 10  college                   164 non-null    str
 11  college_games_played      164 non-null    int64
 12  career_yards              164 non-null    int64
 13  career_touchdowns         164 non-null    int64
 14  rookie_total_ppr_points   154 non-null    float64
 15  season_positional_finish  154 non-null    float64
 16  fantasy_relevant_binary   154 non-null    float64
dtypes: float64(3), int64(9), str(5)
memory usage: 21.9 KB

In [24]:
# Check Season Count

master_df["season"].value_counts().sort_index()

season
2010     8
2011     8
2012    11
2013     5
2014     9
2015    10
2016     8
2017    11
2018    11
2019     8
2020    11
2021    13
2022     7
2023    10
2024    14
2025    10
2026    10
Name: count, dtype: int64

In [25]:
# Create Train/Test/Predict Split

train_df = master_df[
    (master_df["season"] >= 2010) & 
    (master_df["season"] <= 2022)
].copy()

test_df = master_df[
    (master_df["season"] >= 2023) & 
    (master_df["season"] <= 2025)
].copy()

predict_2026_df = master_df[
    master_df["season"] == 2026
].copy()

print("Train:", train_df.shape)
print("Test:", test_df.shape)
print("Predict 2026:", predict_2026_df.shape)

Train: (120, 17)
Test: (34, 17)
Predict 2026: (10, 17)

In [26]:
# Check Target Columns

target_regression = "rookie_total_ppr_points"
target_classification = "fantasy_relevant_binary"

print("Missing regression targets:")
print("Train:", train_df[target_regression].isnull().sum())
print("Test:", test_df[target_regression].isnull().sum())
print("Predict 2026:", predict_2026_df[target_regression].isnull().sum())

print("\nMissing classification targets:")
print("Train:", train_df[target_classification].isnull().sum())
print("Test:", test_df[target_classification].isnull().sum())
print("Predict 2026:", predict_2026_df[target_classification].isnull().sum())

Missing regression targets:
Train: 0
Test: 0
Predict 2026: 10

Missing classification targets:
Train: 0
Test: 0
Predict 2026: 10

In [27]:
# Save Split Datasets

train_df.to_csv("data/processed/train_2010_2022.csv", index=False)
test_df.to_csv("data/processed/test_2023_2025.csv", index=False)
predict_2026_df.to_csv("data/processed/predict_2026.csv", index=False)

print("Files saved successfully.")

Files saved successfully.